// <auto-generated />
using System;
using ExpensesTrackingApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpensesTrackingApp.Migrations
{
    [DbContext(typeof(ExpensesContext))]
    [Migration("20220624085145_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpensesTrackingApp.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Customer A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Customer C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Customer D"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Customer E"
                        });
                });

            modelBuilder.Entity("ExpensesTrackingApp.Models.Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(19,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(350);

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpensesTrackingApp.Models.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Name = "Project One"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            Name = "Project One"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 2,
                            Name = "Project Two"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            Name = "Project Three"
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 3,
                            Name = "Project Four"
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 4,
                            Name = "Project Three"
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 4,
                            Name = "Project Four"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
